### ISSUE TITLE
Bug with Sexual Experience

### ISSUE THREAD

**Issue by gmchain** [majalistic/tales-of-androgyny#11]
File com/majalis/character/SexualExperience.java, lines 185-187, lines:
`this.horse = this.ogre || addedBuilder.ogre;`
`this.horse = this.bird || addedBuilder.bird;`
`this.horse = this.knot || addedBuilder.knot;`

should be changed to:
`this.ogre = this.ogre || addedBuilder.ogre;`
`this.bird = this.bird || addedBuilder.bird;`
`this.knot = this.knot || addedBuilder.knot;`

**Comment by majalistic** [comment]
Thanks!  Fixed it.
